linuxdeepin/deepin-deb-installer

assets/deepin-deb-installer.desktop

Fixes: desktop-entry-lacks-keywords-entry lintian error.

Add Keywords in desktop file.

---

src/deb-installer/main.cpp
src/deb-installer/utils/eventlogutils.cpp
src/deb-installer/utils/eventlogutils.h

Description: 提交埋点需求，记录软件包安装器启动数据
Log: 提交埋点需求，记录软件包安装器启动数据

feat: 提交埋点需求，记录软件包安装器启动数据

---

src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/dependgraph.cpp
src/deb-installer/model/dependgraph.h
tests/CMakeLists.txt
tests/src/manager/ut_packagemanager.cpp

修复虚包处理问题、软件包安装结果判断、多包安装顺序
Log: 修复软件包安装问题
Bug: https://pms.uniontech.com/bug-view-155843.html,https://pms.uniontech.com/bug-view-152753.html,https://pms.uniontech.com/bug-view-151841.html

fix: 修复软件包安装问题

---

.reuse/dep5
debian/copyright

完善reuse和copyright相关的声明
Log: 完善reuse和copyright相关的声明

fix: 完善reuse和copyright相关的声明

---

.reuse/dep5
LICENSES/LGPL-2.0-or-later.txt

修正dep5中针对kde代码的描述
Log: 修正dep5中针对kde代码的描述

fix: 修正dep5中针对kde代码的描述

---

src/deb-installer/CMakeLists.txt
src/deb-installer/dbus/com.deepin.DebInstaller.service
src/deb-installer/main.cpp
src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/deblistmodel.h
src/deb-installer/singleInstallerApplication.cpp
src/deb-installer/singleInstallerApplication.h
src/deb-installer/view/pages/debinstaller.cpp
src/deb-installer/view/pages/debinstaller.h
tests/src/ut_singleInstallerApplication.cpp

Description: 提交软件包安装器二开dbus接口和单元测试代码
Log: 提交软件包安装器二开dbus接口和单元测试代码

feat: 提交软件包安装器二开dbus接口和单元测试代码

---

src/deb-installer/CMakeLists.txt
src/deb-installer/manager/packagesmanager.cpp

修复虚拟包版本号解析错误
此次改动依赖最新的qapt
Log: 修复虚拟包版本号解析错误
Bug: https://pms.uniontech.com/bug-view-179229.html

fix: 修复虚拟包版本号解析错误

---

src/deb-installer/model/dependgraph.cpp

修复循环依赖导致崩溃
Log: 修复循环依赖导致崩溃
Bug: https://pms.uniontech.com/bug-view-180811.html

fix: 修复循环依赖导致崩溃

---

.tx/deepin.conf
debian/changelog

Description: 更新changelog版本
Log: 更新changelog版本

feat: 修改changelog版本

---

src/deb-installer/model/deblistmodel.cpp

同时兼容V20和V23的控制中心打开方式
Log: 同时兼容V20和V23的控制中心打开方式

feat: 同时兼容V20和V23的控制中心打开方式

---

debian/control

服务器版分支移除签名工具依赖
Log: 服务器版分支移除签名工具依赖

fix: 服务器版分支移除签名工具依赖

---

src/deb-installer/manager/packagesmanager.cpp
tests/src/manager/ut_packagemanager.cpp
tests/src/model/ut_deblistmodel.cpp

fix: 修复单元测试

---

tests/src/model/ut_packageanalyzer.cpp
tests/src/test_main.cpp
tests/src/view/pages/ut_backendprocesspage.cpp
tests/src/view/pages/ut_ddimerrorpage.cpp
tests/src/view/pages/ut_packageselectview.cpp
tests/src/view/widgets/ut_noprocesswidget.cpp
tests/src/view/widgets/ut_packageselectitem.cpp
tests/src/view/widgets/ut_processwidget.cpp
tests/test-prj-running.sh

添加DDIM相关的单元测试
Log: 添加DDIM相关的单元测试

feat: 添加DDIM相关的单元测试

---

debian/changelog

chore: 修改changelog

---

debian/changelog

chore: 设置changelog

---

src/AptInstallDepend/main.cpp

wine应用依赖安装添加调用方校验
Log: wine应用依赖安装添加调用方校验
Bug: https://pms.uniontech.com/bug-view-187177.html

fix: wine应用依赖安装添加调用方校验

---

debian/changelog

chore: 刷新changelog

---

debian/changelog

chore: 刷新版本号

---

src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/packageanalyzer.cpp
src/deb-installer/model/packageanalyzer.h
src/deb-installer/view/pages/debinstaller.cpp
tests/src/manager/ut_packagemanager.cpp

目前将apt后端初始化过程使用界面显示出来，将一定程度缓解启动慢的问题
Log: 缓解启动速度慢的问题
Bug: https://pms.uniontech.com/bug-view-162737.html

fix: 缓解启动速度慢的问题

---

src/deb-installer/model/packagelistview.cpp

修复DDIM下安装确认界面选择无高亮
Log: 修复DDIM下安装确认界面选择无高亮
Bug: https://pms.uniontech.com/bug-view-193197.html

fix: 修复DDIM下安装确认界面选择无高亮

---

src/deb-installer/main.cpp
src/deb-installer/model/packageslistdelegate.cpp
src/deb-installer/view/pages/ddimerrorpage.cpp
src/deb-installer/view/pages/debinstaller.cpp
src/deb-installer/view/pages/singleinstallpage.cpp
src/deb-installer/view/widgets/installprocessinfoview.cpp
src/deb-installer/view/widgets/processwidget.cpp

20230329修复UI专题

---

assets/data/deepin-deb-installer.json
src/deb-installer/manager/DealDependThread.cpp
src/deb-installer/manager/DealDependThread.h
src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/deblistmodel.h
src/deb-installer/utils/hierarchicalverify.cpp
src/deb-installer/utils/hierarchicalverify.h
src/deb-installer/view/pages/multipleinstallpage.cpp
src/deb-installer/view/pages/settingdialog.cpp
src/deb-installer/view/pages/settingdialog.h
src/deb-installer/view/pages/singleinstallpage.cpp

feat: 合并分级管控需求

---

.tx/config
translations/deepin-deb-installer.ts
translations/deepin-deb-installer_az.ts
translations/deepin-deb-installer_bo.ts
translations/deepin-deb-installer_ca.ts
translations/deepin-deb-installer_cs.ts
translations/deepin-deb-installer_de.ts
translations/deepin-deb-installer_es.ts
translations/deepin-deb-installer_fi.ts
translations/deepin-deb-installer_fr.ts
translations/deepin-deb-installer_hi_IN.ts
translations/deepin-deb-installer_hr.ts
translations/deepin-deb-installer_hu.ts
translations/deepin-deb-installer_id.ts
translations/deepin-deb-installer_it.ts
translations/deepin-deb-installer_ms.ts
translations/deepin-deb-installer_nl.ts
translations/deepin-deb-installer_pl.ts
translations/deepin-deb-installer_pt.ts
translations/deepin-deb-installer_pt_BR.ts
translations/deepin-deb-installer_ru.ts
translations/deepin-deb-installer_sq.ts
translations/deepin-deb-installer_sr.ts
translations/deepin-deb-installer_tr.ts
translations/deepin-deb-installer_ug.ts
translations/deepin-deb-installer_uk.ts
translations/deepin-deb-installer_zh_CN.ts
translations/deepin-deb-installer_zh_HK.ts
translations/deepin-deb-installer_zh_TW.ts
translations/policy/policy_pl.ts

更新翻译设置及翻译文件
Log: 更新翻译设置及翻译文件
Influence: 翻译设置 翻译文件

chore: 更新翻译设置及翻译文件

---

tests/src/manager/ut_dealdependthread.cpp
tests/src/model/ut_deblistmodel.cpp
tests/src/utils/ut_hierarchicalverify.cpp
tests/src/view/pages/ut_settingdialog.cpp

添加安全等级设置引导提示测试用例.
Log: Add hierarchical notify unit test case.
Influence: UnitTest

test: Add hierarchical notify unit test case.

---

src/deb-installer/manager/AddPackageThread.cpp
src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/utils/utils.cpp
src/deb-installer/utils/utils.h
src/deb-installer/view/widgets/filechoosewidget.cpp
tests/src/utils/ut_utils.cpp

修改检测远程软件包的方式
1. 修改为黑名单策略,gvfs/cifs挂载方式标识非本地包;
2. 增加读取权限判断.
Log: 修改检测软件包是否为本地路径的方式.
Influence: PackageVerify

fix: Change the way packages are checked for local path.

---

src/deb-installer/manager/packagesmanager.cpp

安装 Wine 软件包时，未根据依赖包架构查询软件包，
而是使用安装包架构，修改为根据 Depends 指定架构查询。
Log: 修复安装Wine软件包时查找了错误的依赖包架构。
Bug: https://pms.uniontech.com/bug-view-205805.html
Influence: WineDepends

fix: Wrong architecture used while install wine package.

---

src/deb-installer/view/pages/multipleinstallpage.cpp
src/deb-installer/view/pages/singleinstallpage.cpp
src/deb-installer/view/pages/singleinstallpage.h

修复单包和多包界面中详情的UI问题
Log: 修复单包和多包界面中详情的UI问题
Bug: https://pms.uniontech.com/bug-view-193971.html
Influence: UI

fix: UI diff for single-page and multi-page.

---

src/deb-installer/view/pages/singleinstallpage.cpp
src/deb-installer/view/pages/singleinstallpage.h
src/deb-installer/view/pages/uninstallconfirmpage.cpp

调整界面布局间距,解决布局不一致和控件跳动问题.
Log: 调整界面布局间距.
Bug: https://pms.uniontech.com/bug-view-193969.html
Bug: https://pms.uniontech.com/bug-view-193153.html
Bug: https://pms.uniontech.com/bug-view-193205.html
Bug: https://pms.uniontech.com/bug-view-157603.html
Influence: UI

fix: Adjust layout spacing and margins.

---

src/AptInstallDepend/installDebThread.cpp
src/deb-installer/main.cpp
src/deb-installer/manager/DealDependThread.cpp
src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/deblistmodel.h
tests/src/manager/ut_packagemanager.cpp

合并 release/eagle 分支修改
PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/223
* https://github.com/linuxdeepin/deepin-deb-installer/pull/225
* https://github.com/linuxdeepin/deepin-deb-installer/pull/226
* https://github.com/linuxdeepin/deepin-deb-installer/pull/228
* https://github.com/linuxdeepin/deepin-deb-installer/pull/230
* https://github.com/linuxdeepin/deepin-deb-installer/pull/231
* https://github.com/linuxdeepin/deepin-deb-installer/pull/232

合并 release/eagle 分支修改

---

src/deb-installer/manager/packagesmanager.cpp

优化虚包安装策略，旧版软件包仅处理首个匹配的
虚包，不会遍历其它虚包，可能不满足最优策略。
之前几笔修复调整了在或包依赖时虚包的处理，
现在增加对单独依赖虚包的处理，允许查找后续
虚包实现包以取得影响最小的依赖关系。
Log: 优化虚包安装策略
Bug: https://pms.uniontech.com/bug-view-229757.html
Influence: VirtualPackage

fix: Optimize virtual pkg install strategy.

---

src/deb-installer/manager/packagesmanager.cpp

chore: Add comment details.

---

src/deb-installer/view/pages/debinstaller.cpp
src/deb-installer/view/widgets/filechoosewidget.cpp
src/deb-installer/view/widgets/filechoosewidget.h
tests/src/view/widgets/ut_filechoosewidget.cpp

移除清除焦点的代码
Log: 移除清除焦点的代码
Influence: FocusWidget

fix: Remove clear focus code

---

src/deb-installer/manager/AddPackageThread.cpp
src/deb-installer/manager/AddPackageThread.h
src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/deblistmodel.h
src/deb-installer/utils/utils.cpp
src/deb-installer/view/pages/debinstaller.cpp
src/deb-installer/view/pages/debinstaller.h
translations/deepin-deb-installer_zh_CN.ts
translations/deepin-deb-installer_zh_HK.ts
translations/deepin-deb-installer_zh_TW.ts

将无权限和不在本地两种情况分开处理，走各自的业务，触发不同信号，弹出准确的警告信息
Log: 修复安装时的错误提示
Bug: https://pms.uniontech.com/bug-view-258605.html

fix: Error message during installation

---

src/deb-installer/model/packageanalyzer.h
src/deb-installer/uab/uab_backend.cpp
src/deb-installer/uab/uab_backend.h
src/deb-installer/uab/uab_defines.h
src/deb-installer/uab/uab_process_controller.cpp
src/deb-installer/uab/uab_process_controller.h
src/deb-installer/utils/package_defines.h
src/deb-installer/utils/utils.cpp
src/deb-installer/utils/utils.h
tests/CMakeLists.txt
tests/src/uab/ut_uab_backend.cpp
tests/src/uab/ut_uab_process_controller.cpp

[feat: uab package backend](https://github.com/linuxdeepin/deepin-deb-installer/commit/4fd0413bd56cdb616f89a900b423079934e6e198) 
Add UabBackend;
Uab package meta data parser;
Init package list from `ll-cli list`.
Log: Add uab package backend
Influence: uab-backend
[feat: uab package process controller](https://github.com/linuxdeepin/deepin-deb-installer/commit/8fb3f488a8cd39dc5d9cef4586f76c3f69192cfe) 
Add UabProcessController;
Suppport uab package install/uninstall/upgrade.
Log: Add uab package process controller
Influence: uab-package

feat: uab package backend and process controller

---

src/deb-installer/manager/packagesmanager.cpp

As title.
Log: Disable providesEnhance in the community edition.

fix: disable providesEnhance in the community edition

---

src/deb-installer/uab/uab_dbus_package_manager.cpp
src/deb-installer/utils/utils.cpp

Update uab file mimetype;
Move uninstall uab package process to thread
to avoid blocking threads.
Log: Update uab mimetype and uninstall process.

fix: update uab mimetype and uninstall process

---

src/deb-installer/view/pages/AptConfigMessage.cpp
src/deb-installer/view/pages/ddimerrorpage.cpp
src/deb-installer/view/pages/multipleinstallpage.cpp
src/deb-installer/view/pages/packageselectview.cpp
src/deb-installer/view/pages/singleinstallpage.cpp
src/deb-installer/view/pages/uninstallconfirmpage.cpp

As title.
Change the height of the button accroding to the size mode.
Log: Adapt compact mode.
Bug: https://pms.uniontech.com/bug-view-279783.html
Influence: compact-mode

fix: adapt compact mode

---

src/AptInstallDepend/installDebThread.cpp
src/AptInstallDepend/installDebThread.h
src/deb-installer/compatible/compatible_defines.h
src/deb-installer/immutable/immutable_backend.cpp
src/deb-installer/immutable/immutable_backend.h
src/deb-installer/immutable/immutable_process_controller.cpp
src/deb-installer/immutable/immutable_process_controller.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/deblistmodel.h
src/deb-installer/utils/package_defines.h
src/deb-installer/view/pages/AptConfigMessage.cpp
tests/CMakeLists.txt

Add immutable system installation support:
- Add immutable system constants and commands
- Add immutable process controller / backend integration
- Move error codes to package_defines.h
Log: Add support for package operations on immutable system
Influence: immutable

feat: Add immutable system support

---

debian/changelog

Bump version to 6.5.3
Log: Bump version to 6.5.3

chore: Bump version to 6.5.3

---

translations/deepin-deb-installer.ts
translations/deepin-deb-installer_zh_CN.ts
translations/deepin-deb-installer_zh_HK.ts
translations/deepin-deb-installer_zh_TW.ts

修改翻译错误提示
Bug: https://pms.uniontech.com/bug-view-291851.html
Log: 修改翻译错误提示

fix: 修改翻译错误提示

---

src/AptInstallDepend/installDebThread.cpp
src/AptInstallDepend/installDebThread.h
src/deb-installer/compatible/compatible_backend.cpp
src/deb-installer/compatible/compatible_backend.h
src/deb-installer/compatible/compatible_defines.h
src/deb-installer/compatible/compatible_json_parser.cpp
src/deb-installer/compatible/compatible_json_parser.h
src/deb-installer/compatible/compatible_process_controller.cpp
src/deb-installer/compatible/compatible_process_controller.h
src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/model/abstract_package_list_model.h
src/deb-installer/model/deblistmodel.cpp
src/deb-installer/model/packageanalyzer.cpp
src/deb-installer/utils/deb_package.h
src/deb-installer/view/pages/singleinstallpage.cpp
src/deb-installer/view/pages/singleinstallpage.h
tests/CMakeLists.txt
tests/src/compatible/ut_compatible_json_parser.cpp

- Added app compatibility check to verify package support for rootfs
- Enhanced compatible mode with JSON format communication
- Added loading UI during compatibility check
- Improved rootfs detection and package installation workflow
- Added current user handling for compatible operations
Log: Enhanced compatible mode with app compatibility check
and improved user experience.
Task: https://pms.uniontech.com/story-view-35825.html

feat: Add app compatibility check and enhance compatible mode

---

debian/changelog

Bump version to 6.5.6
Log: Bump version to 6.5.6

chore: Bump version to 6.5.6

---

src/deb-installer/uab/uab_package_list_model.cpp

As title.
Log: fix a hangs issue.
Bug: https://pms.uniontech.com/bug-view-292077.html

fix: app hangs when install uab without linglong

---

debian/changelog

Bump version to 6.5.8
Log: Bump version to 6.5.8

chore: Bump version to 6.5.8

---

src/deb-installer/compatible/compatible_backend.cpp
src/deb-installer/compatible/compatible_process_controller.cpp

The default wait timeout for QProcess is 30s.
But the compatible mode init time may exceed,
increase the wait time for init.
Log: fix wrong rootfs name.
Bug: https://pms.uniontech.com/bug-view-306523.html

fix: get rootfs list incorrect

---

src/deb-installer/manager/packagesmanager.cpp
src/deb-installer/manager/packagesmanager.h
src/deb-installer/model/deblistmodel.cpp

As title.
Log: remove unnecessary check.
Bug: https://pms.uniontech.com/bug-view-307921.html

fix: remove duplicate package status detections.

---

src/deb-installer/model/deblistmodel.cpp

As ttile.
Log: remove unnecessary check.
Bug: https://pms.uniontech.com/zentao/bug-view-307705.html

fix: remove unnecessary check
