src/AptInstallDepend/installDebThread.cpp
原因是代码中写死了必须安装deepin-wine-helper，而部分机型并无此软件包
与相关负责人沟通后，直接从代码中移除此项，完全根据软件包本身的依赖配置进行安装
Log: 修复部分机型无法正确安装带deepin-wine依赖的软件包
Bug: https://pms.uniontech.com/bug-view-145897.html
=> fix: 修复部分机型无法正确安装带deepin-wine依赖的软件包

src/deb-installer/model/deblistmodel.cpp
原因推测是DTK新增了专用设备系统的代号，而软件内部没有增加相关的判断
解决方法是额外增加判断，判断依据和UOS专业版保持一致
Log: 修复UOS专用设备系统下不校验软件包签名和开发者模式
Bug: https://pms.uniontech.com/bug-view-148343.html
=> fix: 修复UOS专用设备系统下不校验软件包签名和开发者模式

src/deb-installer/model/packagelistview.cpp
原因是没有处理焦点切出事件
解决方法是添加对应的处理代码
Log: 修复tab切出安装包列表后，快捷键任然可以操作安装包列表
Bug: https://pms.uniontech.com/bug-view-139853.html
=> fix: 修复tab切出安装包列表后，快捷键任然可以操作安装包列表

src/deb-installer/model/deblistmodel.cpp
原因是DDialog支持使用ESC按键退出，此时会发出rejected信号
解决方法是接收此信号并按reject流程进行处理
Log: 修复部分对话框未处理ESC按键
Bug: https://pms.uniontech.com/bug-view-111212.html
=> fix: 修复部分对话框未处理ESC按键

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/model/deblistmodel.cpp
原因是软件主干流程直接进入了可配置包的安装流程，导致没有安装对应的依赖就直接进入报错流程
解决方法是先判断包是否存在依赖，优先解决依赖问题，随后再走配置安装流程
Log: 修复无法正确安装同时为可配置的包和需要安装依赖的包
Bug: https://pms.uniontech.com/bug-view-149885.html,https://pms.uniontech.com/bug-view-149635.html
=> fix: 修复无法正确安装同时为可配置的包和需要安装依赖的包

src/deb-installer/utils/utils.cpp, src/deepin-deb-installer-dev/status/PackageSigntureStatus.cpp
原因是校验签名只给了30秒时间，超时后会强制杀死进程
修改方法是去除时间限制
Log: 修复超大安装包校验签名失败
=> fix: 修复超大安装包校验签名失败

src/deb-installer/manager/AddPackageThread.cpp, src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/view/widgets/filechoosewidget.cpp
变化：安装存在于诸如 /dev/shm 等 tmpfs 中的 deb 时，不再提示`只能安装本地的deb包`，而是允许安装。
注：在 V15 以及早期的 V20 中我记得都是可以直接通过 __软件包安装器__ 安装被下载到 /dev/shm 中的 deb 包的，后续是因为安全原因还是疏漏了或是其它原因不支持了呢～
=> fix: when installing deb from tmpfs such as /dev/shm/, `You can only install local deb packages` is thrown.

src/deepin-deb-installer-dev/status/PackageStatus.cpp
usleep function need header
Log:
=> fix: debian build missing header

src/deb-installer/manager/packagesmanager.cpp
原来是只要多个或关系的依赖有一个可以解决，就不继续判断后续的依赖
目前修改为多个或关系的依赖有一个是已经就绪，就不继续判断后续的依赖
Log: 修复或依赖的判断逻辑
Bug: https://pms.uniontech.com/bug-view-139517.html
=> fix: 修复或依赖的判断逻辑

src/deb-installer/model/dependgraph.cpp, src/deb-installer/model/dependgraph.h
Description: 删除包指针释放，但是依赖图表里面存放的包指针没有删除，导致访问野指针程序崩溃。在删除包的时候，需要同步删除依赖图表里面 的包指针。
Log: 拖拽较多包到软件包安装器中后，右键逐个删除包会使软件包安装器崩溃
Bug: https://pms.uniontech.com/bug-view-179891.html
=> fix: 拖拽较多包到软件包安装器中后，右键逐个删除包会使软件包安装器崩溃

src/deb-installer/utils/utils.cpp
原因是之前在V23分支上修cppcheck问题时，修改了对验签工具的调用参数，导致传入的路径前后多了两个冒号
解决方法是去掉冒号
Log: 修复签名校验失败
Bug: https://pms.uniontech.com/bug-view-186037.html
=> fix: 修复签名校验失败

src/deb-installer/view/pages/debinstaller.cpp
原因是没有对close event做处理，导致可以使用alt+f4进入
解决方法是在close event里监控外部控件的状态，当无法使用控件按钮退出时，同时不允许相关事件通过
Log: 修复单个deb包安装时可以用alt+f4退出
Bug: https://pms.uniontech.com/bug-view-192353.html
=> fix: 修复单个deb包安装时可以用alt+f4退出

src/deb-installer/view/pages/debinstaller.cpp
原因是被DDIM流程的特殊处理覆盖了
解决方法是加上额外判断，防止被DDIM流程覆盖
Log: 修复重复添加同一deb包，无toast提示
Bug: https://pms.uniontech.com/bug-view-192371.html
=> fix: 修复重复添加同一deb包，无toast提示

src/deb-installer/view/pages/singleinstallpage.cpp
原因是当可以读取中间信息时，将进度条置为零
解决方法是去除对应代码
Log: 修复卸载包过程中进度条可能会归零
Bug: https://pms.uniontech.com/bug-view-192377.html
=> fix: 修复卸载包过程中进度条可能会归零

src/deb-installer/view/widgets/noprocesswidget.cpp
原因是直接设置的固定颜色
解决方法是添加自动变色机制
Log: 修复apt初始化界面的文本不是活动色，无法跟随控制中心设置变化
Bug: https://pms.uniontech.com/bug-view-187389.html
=> fix: 修复apt初始化界面的文本不是活动色，无法跟随控制中心设置变化

src/deb-installer/view/pages/debinstaller.cpp, src/deb-installer/view/pages/multipleinstallpage.cpp
修复收起图标与信息的间距过近
补充修复pr#178引起的无法从启动器或者双击图标进入软件包安装器问题（卡初始化apt界面）
Log: 修复收起图标与信息的间距过近
Bug: https://pms.uniontech.com/bug-view-157601.html
=> fix: 修复收起图标与信息的间距过近

debian/control
master 分支不应强依赖 deepin-elf-sign-tool 工具，
移除对应配置。
Log: 移除对 deepin-elf-sign-tool 的强依赖
Influence: 安装依赖
=> fix: 移除对 deepin-elf-sign-tool 的强依赖

debian/control
移除安装依赖 deepin-elf-verify , control 文件移除对应配置。
master 分支不提供签名校验。
Log: 移除安装依赖 deepin-elf-verify
Bug: https://pms.uniontech.com/bug-view-195557.html
Influence: 安装依赖
=> fix: 移除安装依赖 deepin-elf-verify

assets/data/deepin-deb-installer.json, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/utils/hierarchicalverify.cpp, src/deb-installer/utils/hierarchicalverify.h, src/deb-installer/view/pages/settingdialog.cpp, src/deb-installer/view/pages/settingdialog.h
新版系统引入分级管控进行应用安装分级验签，
添加HierarchicalVerify用于获取分级管控接口，
判断是否进入分级管控流程。根据错误返回值判断
是否为分级管控验签失败错误。
Log: 添加应用安装分级验签处理策略
Influence: 签名校验
=> feat: 添加应用安装分级验签处理策略

src/deb-installer/manager/DealDependThread.cpp, src/deb-installer/manager/DealDependThread.h, src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, src/deb-installer/view/pages/multipleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.cpp
安装wine添加正确校验分级验证输出错误信息，
并在单页/批量安装展示页正确显示错误信息。
Log: 添加分级验签正确处理wine依赖应用提示
Influence: wine依赖安装包签名验证
=> feat: 添加分级验签正确处理wine依赖应用提示

src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, src/deb-installer/utils/hierarchicalverify.cpp
添加分级验签DDIM流程时，安装失败弹出DDIM签名验证失败弹窗时，
不在弹窗处触发状态切换，以正确切换状态。
Log: 添加分级验签时DDIM流程界面逻辑处理
Influence: 分级验签 DDIM
=> feat: 添加分级验签时DDIM流程界面逻辑处理

src/deb-installer/view/pages/debinstaller.cpp
部分场景下, 由于获取后端指针 BackendPtr 等待,
使用 Enter 打开多个软件包可能导致状态异常.
场景无法从单包安装正常切换到多包安装,
因此在更新界面时判断是否切换当前安装界面.
Log: 修复多选几个包，按回车键无法进入批量安装界面
Bug: https://pms.uniontech.com/bug-view-199167.html
Influence: 回车打开软件包 界面切换
=> fix: 修复多选几个包，按回车键无法进入批量安装界面

src/deb-installer/model/deblistmodel.cpp, tests/src/manager/ut_dealdependthread.cpp, tests/src/manager/ut_packagemanager.cpp, tests/src/model/ut_deblistmodel.cpp, tests/src/ut_singleInstallerApplication.cpp, tests/src/utils/ut_hierarchicalverify.cpp
添加分级管控UT代码，覆盖分级管控接口，
直接调用接口部分代码，并对可能影响其它
功能的分级管控接口在测试时进行关闭处理
Log: 添加分级管控UT代码
Influence: UT
=> test: 添加分级管控UT代码

assets/data/deepin-deb-installer.json, src/deb-installer/manager/DealDependThread.cpp, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, src/deb-installer/utils/hierarchicalverify.cpp, src/deb-installer/utils/hierarchicalverify.h, src/deb-installer/view/pages/settingdialog.cpp, src/deb-installer/view/pages/settingdialog.h, translations/deepin-deb-installer.ts, translations/deepin-deb-installer_az.ts, translations/deepin-deb-installer_bo.ts, translations/deepin-deb-installer_ca.ts, translations/deepin-deb-installer_cs.ts, translations/deepin-deb-installer_es.ts, translations/deepin-deb-installer_fi.ts, translations/deepin-deb-installer_hu.ts, translations/deepin-deb-installer_ms.ts, translations/deepin-deb-installer_nl.ts, translations/deepin-deb-installer_pl.ts, translations/deepin-deb-installer_pt.ts, translations/deepin-deb-installer_sq.ts, translations/deepin-deb-installer_ug.ts, translations/deepin-deb-installer_uk.ts, translations/deepin-deb-installer_zh_CN.ts, translations/deepin-deb-installer_zh_HK.ts, translations/deepin-deb-installer_zh_TW.ts
添加安全等级设置引导提示，分级管控
提示调整为安装完成后统一提示。
在设置菜单中添加跳转链接，屏蔽旧版配置。
添加翻译文件。
Log: 添加安全等级设置引导提示
Task: https://pms.uniontech.com/story-view-28999.html
Influence: 分级管控
=> feat: 添加安全等级设置引导提示

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/deblistmodel.cpp
卸载软件包时过滤标记为 Conflict/Replace/Break 的反向依赖包,
这些依赖包并非直接依赖待卸载的软件包,仅移除标记为 Depends 的包.
Log: 修复卸载软件包时卸载了标记"破坏"的反向依赖包
Bug: https://pms.uniontech.com/bug-view-208617.html
Influence: UninstallPcakge
=> fix: Remove package will remove "breaks" reverse depends.

src/deb-installer/manager/packagesmanager.cpp
在 Realse 模式下，某些场景后续调用 QLatin1String 时可能访问失败，
内存被释放，修改为获取数据时即拷贝数据。
Log: 读取从 QApt 返回的 QLatin1String 时可能被释放
Influence: CheckConflict
=> fix: Read QLatin1String returned from QApt may be freed.

src/deb-installer/model/deblistmodel.cpp
开发者模式验签流程时,弹窗前往的是“通用”页面,而不是
“开发者模式”页面,调整DBus接口,以正常跳转.
Log: 跳转到“开发者模式”页面而不是“通用”页面.
Bug: https://pms.uniontech.com/bug-view-209873.html
Influence: DevelopMode
=> fix: Jump to develop mode page instand of common info page.

src/deb-installer/model/deblistmodel.cpp
对话框默认布局过宽,仅限制默认宽度,欠考虑大字号下
默认对话框高度,在初始化时调整内容最低高度.
Log: 对话框字体在大字号下显示不全
Bug: https://pms.uniontech.com/bug-view-201611.html
Influence: DialogText
=> fix: Dialog text disappear when using large font size.

debian/changelog
Update version to 6.0.13
相关PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/206
* https://github.com/linuxdeepin/deepin-deb-installer/pull/208
* https://github.com/linuxdeepin/deepin-deb-installer/pull/209
* https://github.com/linuxdeepin/deepin-deb-installer/pull/210
* https://github.com/linuxdeepin/deepin-deb-installer/pull/211
* https://github.com/linuxdeepin/deepin-deb-installer/pull/213
* https://github.com/linuxdeepin/deepin-deb-installer/pull/214
* https://github.com/linuxdeepin/deepin-deb-installer/pull/215
* https://github.com/linuxdeepin/deepin-deb-installer/pull/216
Log: Update version to 6.0.13
=> chore: Update version to 6.0.13

debian/changelog
[Community] Update version to 6.0.14
相关PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/198 
至
* https://github.com/linuxdeepin/deepin-deb-installer/pull/216
Log: [Community] Update version to 6.0.14
=> chore: [Community] Update version to 6.0.14

src/deb-installer/manager/packagesmanager.cpp, src/deepin-deb-installer-dev/status/PackageStatus.cpp, src/deepin-deb-installer-dev/status/PackageStatus.h, tests/src/manager/ut_packagemanager.cpp
在判断冲突包标识时,仅考虑conflicts,未处理conflicts和
replaces结合使用的场景,更新判断replaces标识.
* 更新了 PackagesManager 的UT.
Log: 修复conflicts和replaces结合使用报告冲突的问题
Bug: https://pms.uniontech.com/bug-view-214693.html
Influence: PackageInstall
=> fix: Fix package conflicts and replaces depends error.

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h
Wine包升降级依赖中i386、amd64架构混用，和安装包
架构不同，使用主线基于包架构的版本存在识别错误。
修改Wine包依赖识别逻辑，未标识架构的将使用默认
包顺序，并判断安装包版本。
Log: 修复安装、升降级Wine应用依赖冲突的问题
Influence: Wine
Change-Id: I1b0b571133cfca62e3ab44887ce7492a7ad170d8
=> fix: Install wine package depends detection error.

src/deb-installer/main.cpp, src/deb-installer/manager/DealDependThread.cpp, src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, tests/src/manager/ut_packagemanager.cpp
在递归解析软件包依赖时，统一使用了安装包架构而不是
指向的软件包架构，修改为基于依赖包架构继续解析。
例如：i386软件包可能依赖amd64软件包，对amd64软件包
的依赖将以amd64架构解析，而不是统一使用i386架构。
添加判断是否指定安装包架构类型，未指定的依赖包
将按照安装包架构进行判断。
部分软件包提供多架构支持，例如部分 amd64 软件包
同样提供 i386 支持。
Bug: https://pms.uniontech.com/bug-view-220943.html
Bug: https://pms.uniontech.com/bug-view-220019.html
=> fix: Fix wine depends detect error.

src/deb-installer/manager/packagesmanager.cpp
不再对包提供的 provides 包检测架构，
在 amd64/i386 场景下可以满足需求。
Log: 修复部分场景对多架构包依赖的识别错误
Bug: https://pms.uniontech.com/bug-view-222531.html
=> fix: Remove check provides architecture.

debian/changelog
Bump version to 6.0.16
PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/223
* https://github.com/linuxdeepin/deepin-deb-installer/pull/225
* https://github.com/linuxdeepin/deepin-deb-installer/pull/226
Log: Bump version to 6.0.16
=> chore: Bump version to 6.0.16

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h
修复同时存在虚包依赖/或依赖时检测错误,
旧版流程基于包不会重复给出ok结果,
引入考虑虚包场景,检测包和实际包名不一致,
导致依赖包未能正常安装.
含虚包依赖/或依赖检测过程:
1. 检测前清理缓存状态;
2. 顺序遍历(后续依赖可能已安装)或依赖;
3. 依赖中存在非ok依赖,缓存包依赖状态;
4. 检测到重复包,返回缓存状态,而不是直接返回ok.
Issue: https://pms.uniontech.com/bug-view-212307.html
Influence: ProvidesDepends OrDepends
=> fix: Detect Provides/Or dependencies error.

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/model/deblistmodel.cpp
安装失败后，界面列表控件在光标移动时会访问
错误原因更新tips. 错误日志在查找函数中打印。
移除在可能重复访问函数中的日志，应调整为在
压入错误信息时单次打入。
Log: 安装失败后持续打印无用日志。
Bug: https://pms.uniontech.com/bug-view-225161.html
=> fix: Print useless log after install failed.

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, tests/src/manager/ut_packagemanager.cpp
或包中包含虚包时，仅匹配了第一个虚包提供包,
不能自动切换到其它提供包，调整或包依赖解析，
将续保所有实现包添加到或包依赖列表中，满足遍历。
Log: 修复虚包、或包共用依赖满足问题
Influence: ProvidesDepends
=> fix: or/provides depends error when first pkg fails.

src/AptInstallDepend/installDebThread.cpp, tests/src/manager/ut_packagemanager.cpp
目前 deepin-deb-installer 使用 KPty 捕获所有通道
进行设置，因此旧版的 installDebThread 手动捕获
输入流程不再响应。
修改输入模式为响应主进程输入，而不是手动管理。
Log: 修复未响应模板设置输入.
Influence: Templates
=> fix: not responding to template settings input.

src/deb-installer/manager/packagesmanager.cpp
优化虚包安装策略，旧版软件包仅处理首个匹配的
虚包，不会遍历其它虚包，可能不满足最优策略。
之前几笔修复调整了在或包依赖时虚包的处理，
现在增加对单独依赖虚包的处理，允许查找后续
虚包实现包以取得影响最小的依赖关系。
Log: 优化虚包安装策略
Bug: https://pms.uniontech.com/bug-view-229757.html
Influence: VirtualPackage
=> fix: Optimize virtual pkg install strategy.

debian/changelog
[Community] Bump version to 6.0.18
PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/222
* https://github.com/linuxdeepin/deepin-deb-installer/pull/224
* https://github.com/linuxdeepin/deepin-deb-installer/pull/234
Log: [Community] Bump version to 6.0.18
=> chore: [Community] Bump version to 6.0.18

src/deb-installer/manager/packagesmanager.cpp
在包冲突包名中含当前包名时，包安装过滤了这类场景，
但已安装包冲突检测没有，导致后续包升降级时，已安装
包冲突项和当前包一致，出现依赖冲突。
调整安装策略和apt一致，允许安装冲突包名和当前包名
一致的包。
Log: 修复特殊依赖安装冲突
Bug: https://pms.uniontech.com/bug-view-233895.html
Influence: Conflicts
=> fix: Conflicts contain pkg name install failed.

debian/changelog
[Community] Bump version to 6.0.19
PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/237
* https://github.com/linuxdeepin/deepin-deb-installer/pull/239
Log: [Community] Bump version to 6.0.19
=> chore: [Community] Bump version to 6.0.19

debian/changelog
Bump version to 6.0.20
PR:
* https://github.com/linuxdeepin/deepin-deb-installer/pull/230
* https://github.com/linuxdeepin/deepin-deb-installer/pull/231
* https://github.com/linuxdeepin/deepin-deb-installer/pull/232
* https://github.com/linuxdeepin/deepin-deb-installer/pull/233
* https://github.com/linuxdeepin/deepin-deb-installer/pull/236
* https://github.com/linuxdeepin/deepin-deb-installer/pull/238
* https://github.com/linuxdeepin/deepin-deb-installer/pull/241
Log: Bump version to 6.0.20
=> chore: Bump version to 6.0.20

src/deb-installer/view/pages/multipleinstallpage.cpp, src/deb-installer/view/pages/packageselectview.cpp, src/deb-installer/view/pages/packageselectview.h, src/deb-installer/view/pages/singleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.h, src/deb-installer/view/widgets/filechoosewidget.cpp, src/deb-installer/view/widgets/filechoosewidget.h
在每个安装界面设置默认焦点控件
涉及单包/批量/DDIM, 操作中断也会将焦点还原
Log: 在每个安装界面设置默认焦点控件
Influence: FocusWidget
=> fix: Set default focus widget on each page

src/deb-installer/view/pages/debinstaller.cpp
修复加载较大软件包可能导致界面焦点错误
传入包过大可能阻塞线程, 导致界面设置顺序异常,
在解析包前先进行界面设置.
Log: 修复加载较大软件包可能导致界面焦点错误
Influence: FocusWidget
=> fix: UI init wrong when load large package

src/deb-installer/model/deblistmodel.cpp, src/deb-installer/view/pages/ddimerrorpage.cpp, src/deb-installer/view/pages/ddimerrorpage.h, src/deb-installer/view/pages/uninstallconfirmpage.cpp, src/deb-installer/view/pages/uninstallconfirmpage.h
调整默认焦点位置,对话框退出后恢复焦点
Log: 调整默认焦点设置
Bug: https://pms.uniontech.com/bug-view-248153.html
Bug: https://pms.uniontech.com/bug-view-248161.html
Influence: FocusWidget
=> fix: Change default focus widget

src/deb-installer/view/pages/ddimerrorpage.cpp
修复在wayland下焦点未成功设置
Log: 修复在wayland下焦点未成功设置
=> fix: Button focus not work in wayland

src/deb-installer/view/pages/packageselectview.cpp
勾选框高度以文本高度计算，低字号下导致选中
效果无法完全展示，设置最小高度避免此问题
Log: 修复勾选框在低字号下选中效果显示不全
Bug: https://pms.uniontech.com/bug-view-248145.html
Influence: UI
=> fix: The effect of checkbox is not fully displayed

README.md, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/utils/hierarchicalverify.cpp, src/deb-installer/view/pages/ddimerrorpage.cpp, src/deb-installer/view/pages/ddimerrorpage.h, src/deb-installer/view/pages/debinstaller.cpp, src/deb-installer/view/pages/multipleinstallpage.cpp, src/deb-installer/view/pages/packageselectview.cpp, src/deb-installer/view/pages/packageselectview.h, src/deb-installer/view/pages/singleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.h, src/deb-installer/view/pages/uninstallconfirmpage.cpp, src/deb-installer/view/pages/uninstallconfirmpage.h, src/deb-installer/view/widgets/filechoosewidget.cpp, src/deb-installer/view/widgets/filechoosewidget.h, tests/src/utils/ut_hierarchicalverify.cpp, tests/src/view/widgets/ut_filechoosewidget.cpp
Synchronize code.
Only .github / .obs / debian directories are different with release/eagle.
=> Merger from release/eagle

debian/control
Add deepin-elf-verfiy / deepin-elf-sign-tool or depends,
deepin-app-store-runtime is available in community edition.
Log: Add or depends on deepin-elf-verify.
Influence: debian/control
=> feat: deepin-elf-verify or depends

debian/control, src/deb-installer/manager/AddPackageThread.cpp, src/deb-installer/manager/AddPackageThread.h, src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, src/deb-installer/utils/utils.cpp, src/deb-installer/view/pages/debinstaller.cpp, src/deb-installer/view/pages/debinstaller.h, translations/deepin-deb-installer_zh_CN.ts, translations/deepin-deb-installer_zh_HK.ts, translations/deepin-deb-installer_zh_TW.ts
cherry-pick from master  c092f495db0e078342f07bd1d8101d7763a83eb3
sync branch master and release/eagle
Add deepin-elf-verfiy / deepin-elf-sign-tool or depends,
deepin-app-store-runtime is available in community edition.
=> fix: cherry-pick from master and update depends

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/abstract_package_list_model.h, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, src/deb-installer/model/proxy_package_list_model.cpp, src/deb-installer/model/proxy_package_list_model.h, src/deb-installer/singleInstallerApplication.cpp, src/deb-installer/uab/uab_backend.cpp, src/deb-installer/uab/uab_backend.h, src/deb-installer/uab/uab_defines.h, src/deb-installer/uab/uab_package.cpp, src/deb-installer/uab/uab_package.h, src/deb-installer/uab/uab_package_list_model.cpp, src/deb-installer/uab/uab_package_list_model.h, src/deb-installer/uab/uab_process_controller.cpp, src/deb-installer/uab/uab_process_controller.h, src/deb-installer/utils/hierarchicalverify.cpp, src/deb-installer/utils/package_defines.h, src/deb-installer/utils/utils.cpp, src/deb-installer/utils/utils.h, src/deb-installer/view/pages/debinstaller.cpp, src/deb-installer/view/pages/debinstaller.h, src/deb-installer/view/pages/multipleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.cpp, src/deb-installer/view/widgets/error_notify_dialog_helper.cpp, src/deb-installer/view/widgets/error_notify_dialog_helper.h, tests/src/manager/ut_packagemanager.cpp, tests/src/model/ut_deblistmodel.cpp, tests/src/uab/ut_uab_process_controller.cpp
[feat: check linglong env and json parser](https://github.com/linuxdeepin/deepin-deb-installer/commit/f4509915dd85bb823a7371117cdd3841edd8d0ef) 
Check ll-cli environment before install;
Add json style ll-cli output parser;
Deb package has higher priority than uab pacakge.
Log: Check linglong env and json parser
Influence: uab-package
[refactor: update the installer dbus interface](https://github.com/linuxdeepin/deepin-deb-installer/commit/50608f9cd7ab01bcbb0ce6f1aa2bab134c5abe1b) 
Update installer DBus interface to support uab package.
Log: The DBus interface supports uab package.
Influence: uab-package
[fix: tip for installation process](https://github.com/linuxdeepin/deepin-deb-installer/commit/9308cf6f837194888abacbe9417b7ae17d4a5c28) 
Add the wine pre-depends flag function;
Add …
=> feat: linglnog output parser and dbus interface

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, tests/src/manager/ut_packagemanager.cpp
The current version only detects the 'replace' field, 'or depends', 'provides depends' of reverse dependency packages not recognized.
Add targetPackageCanReplace() to detect 'or depends', 'provides depends'. If the installed package can be replaced, continue installation.
Log: Fix uable to install replaceable packages.
Bug: https://pms.uniontech.com/bug-view-275221.html
=> fix: failed to detect replaceable packages

src/deb-installer/manager/packagesmanager.cpp
As title.
Log: Fix wrong state when checking 'or depends'.
Bug: https://pms.uniontech.com/bug-view-275221.html
=> fix: init flag before check 'or depends'

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/deblistmodel.h, src/deb-installer/model/packageslistdelegate.cpp, src/deb-installer/utils/deb_package.cpp, src/deb-installer/utils/deb_package.h, src/deb-installer/view/pages/AptConfigMessage.cpp, src/deb-installer/view/pages/ddimerrorpage.cpp, src/deb-installer/view/pages/multipleinstallpage.cpp, src/deb-installer/view/pages/packageselectview.cpp, src/deb-installer/view/pages/singleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.h, src/deb-installer/view/pages/uninstallconfirmpage.cpp, src/deb-installer/view/widgets/infocontrolbutton.cpp, src/deb-installer/view/widgets/infocontrolbutton.h, translations/deepin-deb-installer.ts, translations/deepin-deb-installer_zh_CN.ts, translations/deepin-deb-installer_zh_HK.ts, translations/deepin-deb-installer_zh_TW.ts
As title.
Change the height of the button accroding to the size mode.
Merge form master f04c07f072e3666ab101908d109f33ecd41e9f74
Log: Adapt compact mode.
Bug: https://pms.uniontech.com/bug-view-279783.html
Influence: compact-mode
[fix: add display of packages to be removed](https://github.com/linuxdeepin/deepin-deb-installer/pull/273/commits/ab0b4d49cdc782ee5ce7315f995d607e2cabd694)
1. Backend package removal management:
- Add interfaces and storage for package removal
- Update removal info during dependency check
2. Frontend removal package display:
- Add new data role for removal packages
- Show removal package hints in install UI
Log: Display warning when installing packages
would remove existing packages.
Bug: https://pms.uniontech.com/bug-view-275401.html
[chore: update …
=> fix: adapt compact mode/add display of packages to be removed

src/deb-installer/manager/packagesmanager.cpp, src/deb-installer/manager/packagesmanager.h, src/deb-installer/model/abstract_package_list_model.h, src/deb-installer/model/deblistmodel.cpp, src/deb-installer/model/packageslistdelegate.cpp, src/deb-installer/utils/deb_package.cpp, src/deb-installer/utils/deb_package.h, src/deb-installer/view/pages/multipleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.cpp, src/deb-installer/view/pages/singleinstallpage.h, src/deb-installer/view/widgets/infocontrolbutton.cpp, src/deb-installer/view/widgets/infocontrolbutton.h, translations/deepin-deb-installer.ts, translations/deepin-deb-installer_zh_CN.ts, translations/deepin-deb-installer_zh_HK.ts, translations/deepin-deb-installer_zh_TW.ts
[fix: add display of packages to be removed](https://github.com/linuxdeepin/deepin-deb-installer/commit/f5810c80f461b85fdda47f649608a44ecc33a92f) 
1. Backend package removal management:
- Add interfaces and storage for package removal
- Update removal info during dependency check
2. Frontend removal package display:
- Add new data role for removal packages
- Show removal package hints in install UI
Log: Display warning when installing packages
would remove existing packages.
Bug: https://pms.uniontech.com/bug-view-275401.html
[chore: update translation](https://github.com/linuxdeepin/deepin-deb-installer/commit/9e797aae328bcb7a17643c281ff72650bbf00401) 
Update recently changes translation,
include compatibility mode and display of uninstalld packages.
Log: Update translation.
Influence: …
=> fix: add display of packages to be removed

src/deb-installer/compatible/compatible_backend.cpp, src/deb-installer/compatible/compatible_backend.h
- Add DISABLE_COMPATIBLE macro to disable compatibility mode features
- Mark CompatibleBackend class with deprecation warning
- Simplify compatibility check functions to return false when disabled
- Retain original code for potential future re-enablement
Note: Changes are temporary, module may be re-enabled in future releases.
Log: Temporarily disable compatibility mode.
=> feat: temporarily disable compatibility mode

src/deb-installer/model/deblistmodel.cpp, translations/policy/com.deepin.pkexec.aptInstallDepend.policy
Keep auth when multi-packages installation;
Enhance installation check, if packge not support to install, deepin-immutable-ctl is not called.
Log: Enable keep auth and enhance installation check.
Influence: immutable
=> fix: enable keep auth / add install check

CMakeLists.txt, src/deb-installer/CMakeLists.txt, tests/CMakeLists.txt
As title.
Log: Format CMakeLists.txt
=> chore: format cmakelists.txt

src/AptInstallDepend/installDebThread.cpp, src/deb-installer/uab/uab_backend.cpp
[fix: assume yes in immutable install](https://github.com/linuxdeepin/deepin-deb-installer/commit/6463a06123ee903c12bc710e117dc780302ec9c0) 
As title.
Log: Fixed an issue that blocked the installation.
Bug: https://pms.uniontech.com/bug-view-291783.html
Influence: immutable
[fix: get uab meta info failed](https://github.com/linuxdeepin/deepin-deb-installer/commit/43d30ff62040cebb36304eb5f84d9ad7c58ab472) 
Require uab file executable,
to get the meta info via --print-meta.
Log: Fix get uab meta info failed.
Bug: https://pms.uniontech.com/bug-view-292129.html
Influence: uab-package
=> fix: install package failed

src/AptInstallDepend/installDebThread.cpp
deepin-immutable-ctl remove not support -y,
but its actually use apt to install/uninstall,
use apt instead.
Log: Fix blocked when uninstall.
Bug: https://pms.uniontech.com/bug-view-291783.html
=> fix: blocked when uninstall

src/AptInstallDepend/installDebThread.cpp, src/deb-installer/immutable/immutable_backend.cpp, src/deb-installer/view/widgets/filechoosewidget.cpp
[fix: change tips color when theme changed](https://github.com/linuxdeepin/deepin-deb-installer/commit/d82ba816702a2938d01253597b54e1782f8d435d) 
As title.
Log: change tips color when theme changed
Bug: https://pms.uniontech.com/bug-view-292139.html
Influence: UI
[feat: update immutable config](https://github.com/linuxdeepin/deepin-deb-installer/commit/58268d5540d021622f752ee01ef4882e3c563b82) 
As title.
Log: Update immutable config.
=> fix: change tips color and update immutable config

CMakeLists.txt, src/deb-installer/CMakeLists.txt, src/deepin-deb-installer-dev/CMakeLists.txt, tests/CMakeLists.txt
Use cmake to find the depend qapt-qt6 or qapt and link it.
Log: Fix build with qapt-qt6
=> fix: Fix build with qapt-qt6

src/deb-installer/process/Pty.cpp, src/deb-installer/process/Pty.h, src/deb-installer/process/kptyprocess.cpp, src/deb-installer/process/kptyprocess.h
channel setting function is blocked after Qt6 adaptation, use setChildProcessModifier() replace setupChildProcess().
Log: Fix no install log output.
Bug: https://pms.uniontech.com/bug-view-303125.html
=> fix: no install log output

debian/changelog, src/deb-installer/compatible/compatible_backend.cpp, src/deb-installer/view/pages/singleinstallpage.cpp
[fix: init rootfs first](https://github.com/linuxdeepin/deepin-deb-installer/commit/9674805f560924ff9dc509c2a90ca72c76c5784d) 
Compatible app check is not ready,
but we need a way to init rootfs.
This is a temporay changes.
Log: adapt compatible mode.
[chore: bump version to 6.5.7](https://github.com/linuxdeepin/deepin-deb-installer/commit/e2d6b6319cd70d1bb26dffffd4d84048d1cdd537) 
Bump version to 6.5.7
Log: bump version to 6.5.7
=> fix: init rootfs first and bump version to 6.5.7

src/AptInstallDepend/installDebThread.cpp, src/deb-installer/immutable/immutable_process_controller.cpp
Immutable system has been updated.
When downgrading, need specify --allow-downgrades.
Log: can not downgrades.
Bug: https://pms.uniontech.com/bug-view-305705.html
=> fix: can not downgrades

src/deb-installer/model/deblistmodel.cpp
As ttile.
Log: remove unnecessary check with multi package.
Bug: https://pms.uniontech.com/zentao/bug-view-307705.html
=> fix: skip first package check if cached.

src/deb-installer/manager/packagesmanager.cpp
The old commit create soft-link to package if
the path contains space.
But not set the suffix `.deb`, cause the latest
APT can not recognize the package.
Log: fix a package path error.
Bug: https://pms.uniontech.com/bug-view-309051.html
=> fix: wrong linked package name

src/deb-installer/manager/packagesmanager.cpp
1. Use constant to manage .deb file extension
2. Fix missing extension in duplicate file naming
3. Standardize temporary file naming format
Log: fix a path error.
Bug: https://pms.uniontech.com/bug-view-309051.html
=> fix: optimize symbolic link file naming logic

src/deb-installer/model/deblistmodel.cpp
Correct the misnamed macro definition introduced in the previous compilation error fix
Log: fix build error
=> fix: error version judgement
